[#9] 하나의 DTO를 요청DTO과 응답DTO 용도로 책임 분산, 공연 예매 관련 기능의 Test Code 작성
f-lab-edu/ticketing-practice pull request #10
Opened 2024-08-18 20:41 UTC by agi1004

- 공연 예매 관련 Service 목록: 
- [x] PlaceService
- [x] ConcertService
- [x] DistrictService
- [x] SeatService
- [x] ReservationService
- 공연 예매 관련 Controller 목록: 
- [x] PlaceController
- [x] ConcertController
- [x] DistrictController
- [x] SeatController
- [x] ReservationController
- ConcertDto: ConcertDto 추상 클래스를 상속받는 InConcertDto와 OutConcertDto로 책임 분산
- DistrictDto: DistrictDto 추상 클래스를 상속받는 InDistrictDto와 OutDistrictDto로 책임 분산
- SeatDto: 구역 정보를 불러올 때에는 OutSeatDto로 책임 분산
- ReservationDto: ReservationDto 추상 클래스를 상속받는 InReservationDto와 OutReservationDto로 책임 분산
- UserDto: 회원가입은 InUserDto로 책임 분산

2024-08-23 15:35 UTC, f-lab-justin requested changes
Controller에서 InXXDto, OutXXDto와 같이 In, Out이라는 용어를 prefix를 붙였는데, 
혹시 네이밍을 이렇게 정한 이유가 있을까요? 

일반적으로는
이러한 이름의 경우 XXRequest, XXResponse와 같은 용어를 사용하고 있습니다.

참고 부탁드립니다.

2024-08-23 15:35 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/controller/ConcertController.java
> +		inConcertDto.getDistrictDtos().forEach(districtDto -> {
@agi1004 
여기 로직이 컨트롤러에 있는것보다 concertService.create안에 있으면 어떨까요? 
controller에 비즈니스 로직이 있는 것 같습니다.

2024-08-23 15:35 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/domain/concert/Concert.java
> +	public static Concert of(InConcertDto inConcertDto, Place place, Artist artist) {
@agi1004 
domain에서 dto를 받아서 변환함으로써 domain이 dto를 알게 하는것보다, 
dto에 domain으로의 변환 로직으로 푸는 것이
domain이 dto의 변경에 영향을 받지 않도록 하는 방법입니다.

2024-08-25 09:02 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/controller/ConcertController.java
> +		inConcertDto.getDistrictDtos().forEach(districtDto -> {
변경했습니다!

2024-08-25 09:03 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/domain/concert/Concert.java
> +	public static Concert of(InConcertDto inConcertDto, Place place, Artist artist) {
dto에 newEntity 네이밍을 가지는 정적 팩터리 메서드로 선언해서 변경했습니다!

2024-08-26 11:33 UTC, bluebird702 approved these changes
@agi1004 
수고하셨습니다!

2024-08-26 12:03 UTC, bluebird702 reviewed
다시 재처리

2024-08-26 12:04 UTC, f-lab-justin approved these changes
@agi1004 
수고하셨습니다!

2024-08-27 10:39 UTC, merged