[#3] Gradle로 수정, Spring REST Docs 세팅, User의 API와 기능 구현
f-lab-edu/ticketing-practice pull request #4
Opened 2024-07-08 09:08 UTC by agi1004

- 회원가입
POST /api/users
- 모든 회원 검색 
GET /api/users
- 회원 1명 검색 
GET /api/users/{user_id}
- 회원 정보 수정 
PUT /api/users/{user_id}
- 회원 탈퇴 
DELETE /api/users/{user_id}
- 회원 1명이 작성한 게시글 목록
GET /api/users/{user_id}/articles
- 회원 1명이 작성한 게시글 댓글 목록
GET /api/users/{user_id}/article-comments
- 회원 1명이 작성한 콘서트 댓글 목록
GET /api/users/{user_id}/concert-comments
- 회원 1명의 콘서트 찜 목록
GET /api/users/{user_id}/concert-wishlists
- 회원 1명의 아티스트 찜 목록
GET /api/users/{user_id}/artist-wishlists
- 회원 1명이 예매한 공연 목록
GET /api/users/{user_id}/reservations
- 회원 1명이 예매한 공연 1개 취소
DELETE /api/users/{user_id}/reservations/{reservation_id}

2024-07-08 13:00 UTC, f-lab-justin requested changes
@agi1004 
피드백 한번 살펴봐주세요!

2024-07-08 13:00 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +	@PostMapping("")
("")는 없어도 됩니다!

2024-07-08 13:00 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +	public UserController(UserService userService) {
@agi1004 
생성 로직은 가능하면 일관되게 사용하시면 좋습니다~! 
여기는 생략해도 될듯요!

2024-07-08 13:00 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +		if (bindingResult.hasErrors()) {
@agi1004 
runtime exception으로 처리해서 exception handler가 에러 response를 리턴하는 형태로 구현해보세요!

2024-07-08 13:00 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +			userService.addUser(userCreateForm.getUsername(), userCreateForm.getPassword1(), userCreateForm.getNickname(), userCreateForm.getEmail(),
@agi1004 
parameter가 3개가 넘어가면 DTO 클래스로 묶어주는 것이 좋습니다.

2024-07-08 13:00 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +		}
@agi1004 
위와 같이 예외처리하는 부분을 살펴보세요!

Spring의 ExceptionHandler로 검색하시면 많이 나옵니다!

2024-07-08 13:00 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +	public ResponseEntity<List<User>> getAllUsers() {
@agi1004 
Spring에서 간단한 설정 시 ResponseEntity를 안써줘도 되는데요! 한번 찾아보세요!

2024-07-08 13:00 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +	public ResponseEntity<User> updateUser(@PathVariable("userId") Long id,
@agi1004 
줄이 안맞는 부분은 코드를 보기 어렵게 하기 때문에 꼭 맞춰보세요!
lint에 대해서도 한번 살펴보시기 바랍니다!

2024-07-08 13:00 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +
@agi1004 
set함수를 사용하지 않고 상태를 변화시키는 함수로 작성해주면 좋을 것 같습니다!

2024-07-08 13:00 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +		return ResponseEntity.noContent().build();	// 204 No Content 반환
@agi1004 
DELETE는 보통 200을 많이 쓰고, response로 entity ID를 내려주는 경우가 일반적입니다.

2024-07-08 13:00 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +		if (user == null) {
@agi1004 
null은 최대한 사용하지 않도록 일관성 있게 작성하시면 좋습니다. 
그리고 보통의 경우 사용자가 없는 경우라던가, 비지니스 로직을 수행하는데 기본적인 엔티티가 없는 경우에도 exception으로 처리하는 경우가 많습니다. 

그러면 if(EntityId == null)과 같은 처리가 필요 없습니다.

if(xxxx == null) 와 같은 코드는 최대한 사용하지 않도록 노력해봅시다.

2024-07-08 13:00 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/service/UserSecurityService.java
> +		User user = optionalUser.get();
@agi1004 
Optional의 chaning함수들을 사용하면 좀 더 깔끔하게 작성할 수도 있습니다.
map등의 함수 사용법을 한번 살펴보세요!

2024-07-08 13:00 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/service/UserSecurityService.java
> +		if ("ADMIN".equals(user.getRole())) {
@agi1004 
Enum값을 사용할 수 있도록 해봅시다!

2024-07-08 13:00 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/service/UserSecurityService.java
> +		if ("ADMIN".equals(user.getRole())) {
@agi1004 
조건이 1개이면 if-else, 2개 이상이면 switch-case를 추천합니다!

2024-07-08 13:00 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/service/UserService.java
> +	private final UserRepository userRepository;
@agi1004 
좀 더 도메인 별로 나눠서 처리할 수 있도록 해놓으면 더 좋을 것 같습니다.

2024-07-08 13:00 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/service/UserService.java
> +	public User getUser(String username) {
@agi1004 
Optional을 좀 더 잘쓰면 더 간결하게 작성할 수 있습니다!!

```java
public User getUser(String username) {
       return userRepository.findByUsername(username)
                                            .orElseThrow(IllegalStateException::new);                                              
}
```

2024-07-11 12:36 UTC, agi1004 commented
커밋을 하는 과정에서 충돌이 일어나서 이전 변경 사항이 적용되지 않고 아예 모두 새로 커밋이 되어버렸습니다.. ㅠㅠ

2024-07-11 12:36 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +	@PostMapping("")
고쳤습니다!

2024-07-11 12:36 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +	public UserController(UserService userService) {
고쳤습니다!

2024-07-11 12:37 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +		if (bindingResult.hasErrors()) {
고쳤습니다!

2024-07-11 12:41 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +		if (bindingResult.hasErrors()) {
// 회원 생성
	@Transactional
	public Long createUser(UserDto userDto) {
		// 비밀번호와 비밀번호 확인이 다를 경우 400(잘못된 요청) 던지기
		if (!userDto.getPassword1().equals(userDto.getPassword2())) {
			throw new IllegalArgumentException("비밀번호와 비밀번호 확인이 다릅니다.");
		}
		
		// username으로 회원 조회가 된 경우 중복 객체이므로 409(충돌) 던지기
		userRepository.findByUsername(userDto.getUsername()).ifPresent(duplicatedUser -> {
			throw new DuplicatedExcpetion("username: " + userDto.getUsername() + "은 이미 존재하는 회원입니다.");
		});
		
		// Dto에서 Entity로 변환
		User user = UserDto.toEntity(userDto, passwordEncoder);
		
		User createdUser = userRepository.save(user);
		
		return createdUser.getId();
	}

UserController에서 예외 처리하던 것을 UserService로 옮겼습니다.

2024-07-11 12:44 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +			userService.addUser(userCreateForm.getUsername(), userCreateForm.getPassword1(), userCreateForm.getNickname(), userCreateForm.getEmail(),
```
Long userId = userService.createUser(userDto);
```
createUser 메서드는 바로 위에 보낸 코멘트처럼 수정했습니다.

2024-07-11 12:45 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +		}
이것도 예외는 UserService의 createUser 메서드에서 처리했습니다.

2024-07-11 12:47 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +
```
user.update(userUpdateRequest.getNickname(), userUpdateRequest.getEmail(), userUpdateRequest.getPhone());
```
User 클래스에 update 메서드를 만들었습니다.
```
// 특정 필드만 수정하는 메서드
public void update(String nickname, String email, String phone) {
this.nickname = nickname;
this.email = email;
this.phone = phone;
}
```

2024-07-11 12:48 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +		return ResponseEntity.noContent().build();	// 204 No Content 반환
```
return ResponseEntity.status(HttpStatus.OK).body("회원(id: " + userId + ") 탈퇴에 성공했습니다.");
```

2024-07-11 12:51 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +		if (user == null) {
```
// 회원 1명이 작성한 게시글 목록 조회
@GetMapping("/{userId}/articles")
public ResponseEntity<List<Article>> getArticlesByUserId(
										@PathVariable("userId") Long userId) {
  List<Article> articles = userService.readArticlesByUserId(userId);
  return ResponseEntity.ok(articles);
}
```
```
// 회원 1명이 작성한 게시글 목록 조회
@Transactional
public List<Article> readArticlesByUserId(Long userId) {
  User user = readUser(userId);
  return articleRepository.findByUser(user);
}
```
```
// userId로 회원 조회
	public User readUser(Long userId) {
		return userRepository.findById(userId)
				.orElseThrow(() -> new DataNotFoundException("회원을 찾을 수 없습니다."));
	}
```

2024-07-11 12:53 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/service/UserSecurityService.java
> +		User user = optionalUser.get();
```
@SuppressWarnings("serial")
		User user = userRepository.findByUsername(username)
					.orElseThrow(() -> new UsernameNotFoundException("사용자를 찾을 수 없습니다.") {});
```

2024-07-11 12:55 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/service/UserSecurityService.java
> +		if ("ADMIN".equals(user.getRole())) {
```
switch(user.getRole()) {
	case ADMIN -> {
		// 관리자(ADMIN) 권한을 얻어서 내장 권한 클래스 리스트에 넣음
		authorities.add(new SimpleGrantedAuthority(ADMIN.getRole()));	// 관리자 권한 부여
	}
	case USER -> {
		// 회원(USER) 권한을 얻어서 내장 권한 클래스 리스트에 넣음
		authorities.add(new SimpleGrantedAuthority(USER.getRole()));	// 회원 권한 부여
	}
}
```

2024-07-11 12:56 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/service/UserService.java
> +	public User getUser(String username) {
고쳤습니다!

2024-07-11 13:04 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +	public ResponseEntity<List<User>> getAllUsers() {
https://ksh-coding.tistory.com/89
찾아보니까 @ResponseBody보다는 ResponseEntity가 더 좋다는데 그래도 고쳐야 할까요,,??

2024-07-15 12:29 UTC, f-lab-justin requested changes
@agi1004 
한번 살펴봐 주세요!!

2024-07-15 12:29 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/controller/UserController.java
> +	public ResponseEntity<List<User>> getAllUsers() {
@agi1004 
이 부분은 좋고 나쁜 부분이 있다기 보다는 스프링에서 이런 방법을 제공하니 다른 코드를 볼 때 ResponseEntity를 사용하지 않으면 @ResponseBody방식으로 처리했구나로 이해하면 될 것 같습니다!

2024-07-15 12:29 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/service/UserService.java
> +	}
@agi1004 
generic을 활용해볼 수 있을 것 같습니다!

2024-07-20 20:37 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/service/UserService.java
> +	}
```
// 회원 1명의 엔티티 목록 조회
@Transactional
public <T> List<T> readEntitiesByUserId(Long userId, UserRelatedRepository<T> repository) {
	User user = readUser(userId);
	return repository.findByUser(user);
}
```
제네릭 메서드를 추가했습니다!
```
// 회원 1명이 작성한 게시글 목록 조회
@Transactional
public List<Article> readArticlesByUserId(Long userId) {
	return readEntitiesByUserId(userId, articleRepository);
}
	
// 회원 1명이 작성한 게시글 댓글 목록 조회
@Transactional
public List<ArticleComment> readArticleCommentsByUserId(Long userId) {
	return readEntitiesByUserId(userId, articleCommentRepository);
}
	
// 회원 1명이 작성한 콘서트 댓글 목록 조회
@Transactional
public List<ConcertComment> readConcertCommentsByUserId(Long userId) {
	return readEntitiesByUserId(userId, concertCommentRepository);
}
	
// 회원 1명의 콘서트 찜 목록 조회
@Transactional
public List<ConcertWishlist> readConcertWishlistsByUserId(Long userId) {
	return readEntitiesByUserId(userId, concertWishlistRepository);
}
	
// 회원 1명의 아티스트 찜 목록 조회
@Transactional
public List<ArtistWishlist> readArtistWishlistsByUserId(Long userId) {
	return readEntitiesByUserId(userId, artistWishlistRepository);
}
	
// 회원 1명의 예매 목록 조회
@Transactional
public List<Reservation> readReservationsByUserId(Long userId) {
	return readEntitiesByUserId(userId, reservationRepository);
}
```
다른 메서드들이 제네릭 메서드를 호출하도록 변경했습니다!
```
public interface UserRelatedRepository<T> {
	List<T> findByUser(User user);
}
```
```
public interface ArticleRepository extends JpaRepository<Article, Long>, UserRelatedRepository<Article> {
	List<Article> findByBoard(Board board);		// 한 개의 게시판에 속한 게시글 리스트 찾기
	List<Article> findByUser(User user);		// 한 명의 회원이 작성한 게시글 리스트 찾기
}
```
각각의 레포지토리들이 제네릭 레포지토리를 확장하도록 변경했습니다!

2024-07-22 12:49 UTC, f-lab-justin approved these changes
@agi1004 
수고하셨습니다!

2024-07-25 03:29 UTC, merged