[#5] 자코코(JaCoCo)를 활용한 테스트 커버리지 측정
f-lab-edu/ticketing-practice pull request #6
Opened 2024-07-25 11:42 UTC by agi1004

- User의 기능 모두 테스트 커버리지 측정
- 테스트 커버리지 100% 달성
![테스트 커버리지 100%](https://github.com/user-attachments/assets/723fce62-e32c-4497-a90d-8b57de2532b1)

2024-07-27 08:37 UTC, f-lab-justin requested changes
@agi1004 
확인 부탁드립니다!

2024-07-27 08:37 UTC, f-lab-justin commented on ticketing-practice/src/test/java/com/ticketingberry/controller/UserControllerTest.java
>  		UserDto userDto = new UserDto();
@agi1004 
테스트 코드긴 하지만..습관으로라도 set함수는 가능하면 사용하지 않도록 연습해봅시다!
effective java도 읽어보았으니 왜 get, set함수를 습관적으로 사용하면 안좋은지에 대해서는 인지하고 계시지요??

2024-07-27 08:37 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/service/UserService.java
> +	public User readUserById(Long userId) {
@agi1004 
크리티컬한건 아닌데..보통 엔티티를 찾아오는 동작을 수행하기 때문에 일반적으로 readUser보다는 findUser가 더 적합한 네이밍입니다. userRepository에서 findById를 사용하는 것도 그 예구요. CRUD긴 하지만 Read라고 해서 꼭 Read를 쓰진 않아도 됩니다^^;; 

추가적으로 네이밍을 할 때 해당 entity가 이미 repository나 service이름에 포함되어 있다고 가정하고 해당 entity이름은 넣지 않는 것이 일반적입니다. 

예)
userRepository.findUserById(userId) -> 요렇게 쓸수도 있지만 중복으로 보여질 수 있어서 잘 안사용합니다. 
userRepository.findById(userId) -> O 
userService.findUserById(userId) -> 요렇게 쓸수도 있지만 중복으로 보여질 수 있어서 잘 안사용합니다. 
userService.findById(userId) -> O

참고 부탁드립니다!

2024-07-27 08:37 UTC, f-lab-justin commented on ticketing-practice/src/test/java/com/ticketingberry/controller/UserControllerTest.java
> +		UserDto userDto = new UserDto();
@agi1004 
위의 테스트와 아래에서 사용하는 UserDto생성코드가 중복되는 부분들이 있는데, 테스트용 UserDto를 미리 만들어놓고, 테스트마다 달라야 하는 필드들만 변경해서 사용하시면 관리에 더욱 좋습니다.

2024-07-29 00:00 UTC, agi1004 commented on ticketing-practice/src/test/java/com/ticketingberry/controller/UserControllerTest.java
>  		UserDto userDto = new UserDto();
넵! 기본 생성자로 객체 생성 후 setter를 사용하여 필드를 초기화하면, 객체가 완전히 생성되기 전까지는 일관성이 무너진 상태에 놓이기 때문입니다.
Builder 패턴은 Entity에만 사용하면 되는 줄 알고 Dto에서는 setter를 사용해버렸습니다.
```
userDto = UserDto.builder()
		.username("testuser")
		.password1("password")
		.password2("differentPassword")
		.nickname("테스트")
		.email("testuser@example.com")
		.phone("01012345678")
		.birth("20000101")
		.gender("F")
		.build();
```
변경했습니다!

2024-07-29 00:01 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/service/UserService.java
> +	public User readUserById(Long userId) {
```
public User findById(Long userId)
```
변경했습니다!

2024-07-29 00:02 UTC, agi1004 commented on ticketing-practice/src/test/java/com/ticketingberry/controller/UserControllerTest.java
> +		UserDto userDto = new UserDto();
```
@BeforeEach
void setUp(WebApplicationContext context) {
userDto = UserDto.builder()
		.username("testuser")
		.password1("testpassword")
		.password2("testpassword")
		.nickname("테스트")
		.email("testuser@example.com")
		.phone("01012345678")
		.birth("20000101")
		.gender("F")
		.build();
}
```
변경했습니다!

2024-08-01 14:42 UTC, f-lab-justin requested changes
@agi1004 
확인 부탁드립니다!

2024-08-01 14:42 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/service/UserService.java
> +		User user = findById(userId);
@agi1004 
네이밍이 일관성이 있어야 혼선이 없습니다.
위의 경우 테이블 엔티티 이름을 써서 findArticleCommentsByUserId와 같이 사용했는데,
여기서는 findById로 했을 때 혼선이 있을 것 같습니다. 

여기서도 findUserByUserId와 같이 네이밍 규칙을 맞추면 더 이해하기 용이할 것 같습니다!

2024-08-01 14:42 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/service/UserService.java
> +	public List<Reservation> findReservationsByUserId(Long userId) {
@agi1004 
혹시 여기서 Entities를 사용하신 이유가 어떤걸까요? 
리턴값으로 Reservation을 주고 있는데 함수 이름은 Entities라서 연결이 잘 안되어서요!

2024-08-02 02:13 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/service/UserService.java
> +		User user = findById(userId);
추가적으로 네이밍을 할 때 해당 entity가 이미 repository나 service이름에 포함되어 있다고 가정하고 해당 entity이름은 넣지 않는 것이 일반적입니다.

예)
userRepository.findUserById(userId) -> 요렇게 쓸수도 있지만 중복으로 보여질 수 있어서 잘 안사용합니다.
userRepository.findById(userId) -> O
userService.findUserById(userId) -> 요렇게 쓸수도 있지만 중복으로 보여질 수 있어서 잘 안사용합니다.
userService.findById(userId) -> O

위에서 이렇게 말씀하셔서 고쳤습니다... 원래는 findUserByUserId였습니다.

2024-08-02 02:13 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/service/UserService.java
> +	public List<Reservation> findReservationsByUserId(Long userId) {
// 회원 1명의 엔티티 목록 조회
```
@Transactional
public <T> List<T> findEntitiesByUserId(Long userId, UserRelatedRepository<T> repository) {
	User user = findById(userId);
	return repository.findByUser(user);
}
```
중복 코드는 제네릭 메서드를 만들라고 하셔서 레포지토리의 상위 인터페이스를 매개변수로 받는 제네릭 메서드를 작성했습니다.
그래서 이전 풀 리퀘스트에서는 분명 통과해주셨습니다..

2024-08-02 16:06 UTC, f-lab-justin approved these changes
@agi1004 
findById관련된 부분이 오락가락했네요. 멘토링 때 이야기 드릴게요. 
고생하셨습니다!

2024-08-03 11:45 UTC, merged