[#7] 공연 예매 관련 Entity 기능 구현
f-lab-edu/ticketing-practice pull request #8
Opened 2024-08-05 10:20 UTC by agi1004

- 공연 예매 관련 Entity 목록: 
- [ ] Place
- [ ] Concert (Place 참조)
- [ ] District (Concert 참조)
- [ ] Seat (District 참조)
- [ ] Reservation (User, Seat 참조)
- Controller의 Response를 Entity에서 Dto로 변경

2024-08-05 15:25 UTC, f-lab-justin requested changes
@agi1004 
다음의 내용들을 참고하셔요.
- 객체의 생성로직은 해당 객체 내부로 숨기거나, 별도의 factory class로 만드는 것이 좋습니다. 한번 살펴보셔요. DTO정도의 생성 로직은 factory메소드가 아닌 DTO안에 생성함수에 넣어주어도 됩니다. 
- 백엔드 서버의 경우 모든 API를 일관되게 json으로 요청받고, json으로 응답합니다. POST, PUT도 동일하니 참고하셔요. 
- for문을 쓸 수도 있지만 java8의 stream을 활용하면 좀 더 깔끔하게 코드를 작성할 수 있습니다. 한번 살펴보셔요.

2024-08-05 15:25 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/controller/ConcertController.java
> +	public String addConcert(@Valid @RequestBody ConcertDto concertDto) {
@agi1004 
Post에 대한 응답도 json으로 객체로 내려주면 됩니다. 
일반적으로 최근 application들은 request, response는 모두 json으로 받고 json으로 내려줍니다. 

여기서는 addConcert이기 때문에 어떤 값을 리턴해주는 게 좋을지 저번에 말씀드렸던 마이크로소프트 문서 한번 보시고 어떻게 응답값을 내려주면 좋을지 고민해보세요.

2024-08-05 15:25 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/controller/ConcertController.java
> +		for (DistrictDto districtDto : districtDtoList) {
@agi1004 
요즘은 for문보다 java8의 stream방식을 많이 사용하는 편입니다. 한번 찾아보세요.

2024-08-05 15:25 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/controller/ConcertController.java
> +			ConcertDto concertDto = ConcertDto.builder()
@agi1004 
이러한 ConcertDto의 생성 로직은 ConcertDto안으로 넣는게 좋습니다. 

```java
ConcertDto conceretDto = ConcertDto.of(concert)
```

로 정리해주면 생성로직은 해당 엔티티 안으로 깔끔하게 숨길 수 있습니다.

2024-08-05 15:25 UTC, f-lab-justin commented on ticketing-practice/src/main/java/com/ticketingberry/controller/ConcertController.java
> +	public String modifyConcert(@PathVariable("concertId") Long concertId,
@agi1004 
수정된 엔티티를 json으로 내려주면 됩니다.

2024-08-09 13:55 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/controller/ConcertController.java
> +	public String addConcert(@Valid @RequestBody ConcertDto concertDto) {
ConcertDto로 Response하도록 변경했습니다!

2024-08-09 13:56 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/controller/ConcertController.java
> +		for (DistrictDto districtDto : districtDtoList) {
```
// District와 Seat을 차례대로 저장
concertDto.getDistrictDtos().stream()
.forEach(districtDto -> {
	// Seat 리스트의 값을 제외한 District를 우선 저장
	District district = districtService.create(districtDto, concert);
	// Seat을 District에 차례대로 저장
	districtDto.getSeatDtos().stream()
	.forEach(seatDto -> seatService.create(seatDto, district));
});
```
변경했습니다!

2024-08-09 13:56 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/controller/ConcertController.java
> +			ConcertDto concertDto = ConcertDto.builder()
```
public static ConcertDto of(Concert concert) {
	return ConcertDto.builder()
			.placeId(concert.getPlace().getId())
			.artistId(concert.getArtist().getId())
			.title(concert.getTitle())
			.content(concert.getContent())
			.openedTicketAt(concert.getOpenedTicketAt())
			.performedAt(concert.getPerformedAt())
			.districtIds(concert.getDistricts().stream()
					.map(district -> district.getId())
					.collect(Collectors.toList()))
			.build();
}
```
변경했습니다!

2024-08-09 13:57 UTC, agi1004 commented on ticketing-practice/src/main/java/com/ticketingberry/controller/ConcertController.java
> +	public String modifyConcert(@PathVariable("concertId") Long concertId,
ConcertDto로 Response하도록 변경했습니다!

2024-08-09 15:52 UTC, f-lab-justin approved these changes
@agi1004 
코드가 훨씬 깔끔해졌네요! 
개선할 부분들이 간간히 있지만 이러한 부분은 이후에 다른 코드 수정하면서 보이게 될 때 다시 말씀드릴게요. 

그리고 controller에서 받은 dto를 그대로 service로 넘기는 것에 대한 장단점에 대해서 그전에 잠깐 이야기를 했었던 것 같은데요. 
이부분에 대해서는 멘토링 시간에 다시 한번 이야기해보시지요!
수고하셨습니다.

2024-08-10 04:01 UTC, merged